#!/usr/bin/env python

"""
Usage:
	findFavLang [-i] <username>

	-i	ignores forked repos
"""

import sys,os,re
from mainClass import GitHubAccount, GitHubRepo
import docopt
import pdb

d = docopt.docopt(__doc__)

GitHubName = d['<username>']
ignoreforked = d['-i']

a = GitHubAccount(GitHubName)

if a.getName() == None:
	print "Username %s does not exist." % GitHubName

elif a.getRepos() == None:
	print "User does not have any repos."

elif a.getFavLanguage(ignoreforked) == None:
	print "User has no favourite language."

else:
	print "Favourite language is " + a.getFavLanguage(ignoreforked=ignoreforked)+"."

sys.exit()
